# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - release
notifications:
  email: false
sudo: required
dist: trusty
addons:
   apt:
      packages:
         - xvfb
         - xauth
         - libgtk-3-0
before_install:
  - sudo pip install matplotlib
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia ./test/install_Spikes.jl
  - xvfb-run julia --check-bounds=yes --depwarn=no -e 'Pkg.clone(pwd()); Pkg.build("Spikes"); Pkg.test("Spikes"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("Spikes")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
